// frontend/vuejs-project/src/App.vue

<template>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <router-link class="navbar-brand" to="/">IP Manager</router-link>
    </div>
  </nav>

  <div class="container mt-4">
    <router-view></router-view>
  </div>
</template>

<script>
export default {
  name: 'App'
}
</script>

// frontend/react-project/src/App.js
import React from 'react';
import './App.css';
import IpList from './components/IpList';

function App() {
    return (
        <div className="App">
            <nav className="navbar navbar-dark bg-dark">
                <div className="container">
                    <span className="navbar-brand mb-0 h1">Gestionnaire d'IPs</span>
                </div>
            </nav>
            <IpList />
        </div>
    );
}

export default App;
